# Database settings.
database:
  driverClass: org.h2.Driver
  user: app
  password: app
  url: jdbc:h2:./aplicacion;TRACE_LEVEL_FILE=4;DB_CLOSE_ON_EXIT=FALSE

server:
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8011

# Logging settings.
logging:
  level: INFO
  loggers:
    org.hibernate.SQL: ALL
  appenders:
    - type: console